### ISSUE TITLE
Repository structure for v2024.14.1 is not compliant

### ISSUE THREAD

**Issue by Walissona** [Klangen82/Creality-Control#10]
I'm unable to add integration.
I also tried copying the folder to _custom components, the folder is there, but the integration does not appear available in the store
![erro hacs](https://github.com/user-attachments/assets/0c3b768b-70d9-409a-ac14-0effa1de7cc2)

**Comment by Klangen82** [comment]
Looks like you are trying to add it via HACS and this is not avlible in HACS. So you need to download creality_control folder and place it under \config\custom_components so it looks like this \config\custom_components\creality_control

To note this has just been tested on Creality halot one so no garanty it works with other then this printer

**Comment by Walissona** [comment]
![image](https://github.com/user-attachments/assets/79ed741e-4412-4f44-963c-17f9b65ba6f2)

As I already mentioned, the folder is already there
But when I search the store the integration doesn't appear !
Any other suggestion?

**Comment by Klangen82** [comment]
I don't look right, you should just download the folder creality_control and install it under custom_components, reboot, then you should add integration under settings - devices & services in HA.

![image](https://github.com/user-attachments/assets/47bdd6df-e2df-4339-9c31-37a970ca192e)
![image](https://github.com/user-attachments/assets/f29aee5e-b11c-44e5-ac67-2946150cf597)

**Comment by Walissona** [comment]
it worked!
Actually, I downloaded it and threw the folder there.
The name and structure were wrong.

Tanks !

**Comment by jrspowers** [comment]
> Het werkte! Eigenlijk heb ik het gedownload en de map daar gegooid. De naam en structuur klopten niet.
> 
> Tanks!

hallo,
were you able to connect it to home-assistant ? mine doesn't want to work-it's for an ender 3 v2, but it just won't connect.

**Comment by Walissona** [comment]
> > Het werkte! Eigenlijk heb ik het gedownload en de map daar gegooid. De naam en structuur klopten niet.
> > Tanks!
> 
> hallo, were you able to connect it to home-assistant ? mine doesn't want to work-it's for an ender 3 v2, but it just won't connect.

Follow this https://github.com/Klangen82/Creality-Control/issues/1#issuecomment-2144922969 it will work

**Comment by jrspowers** [comment]
> > > Het werkte! Eigenlijk heb ik het gedownload en de map daar gegooid. De naam en structuur klopten niet.
> 
> > > Tanks!
> 
> > 
> 
> > hallo, were you able to connect it to home-assistant ? mine doesn't want to work-it's for an ender 3 v2, but it just won't connect.
> 
> 
> 
> Follow this https://github.com/Klangen82/Creality-Control/issues/1#issuecomment-2144922969 it will work

Hello, it’s still not working for me on my Ender 3 v2. I can’t get it to show up in Home Assistant, which is really strange, and I’ve followed all the steps listed here. Really unfortunate.

**Comment by Walissona** [comment]
> > > > Het werkte! Eu realmente fiz o download do mapa daar gegooid. O nome e a estrutura do bloco não.
> > 
> > 
> > > > Tanques!
> > 
> > 
> > > 
> > 
> > 
> > > Olá, você conseguiu conectá-lo ao assistente doméstico? O meu não quer funcionar, é para um Ender 3 v2, mas ele simplesmente não conecta.
> > 
> > 
> > Siga este [#1 (comentário)](https://github.com/Klangen82/Creality-Control/issues/1#issuecomment-2144922969) funcionará
> 
> Olá, ainda não está funcionando para mim no meu Ender 3 v2. Não consigo fazer com que apareça no Home Assistant, o que é muito estranho, e segui todos os passos listados aqui. Realmente lamentável.

I imagine it's your version being V2

**Comment by pcartwright81** [comment]
@Walissona If your issue is fixed please close it.
@jrspowers Ender 3 V2 uses next release which has issues or https://github.com/pcartwright81/creality_box_control.
