### ISSUE TITLE
Pasword

### ISSUE THREAD

**Issue by peppeman75** [Klangen82/Creality-Control#2]
L'integrazione richiede per forza il campo password!
Di solito la stampante il locale non ha password, non riesco ad aggiungere la stampante!

English:
The integration necessarily requires the password field! Usually the local printer has no password, I can't add the printer!

**Comment by Klangen82** [comment]
Hi @peppeman75,

It's mandatory to setup a password. On my device it's done via Print settings->Device control->Password

If you do this will it work then?
