### ISSUE TITLE
dont have a password and not sure where to put one if i wanted one. cant get the integration to configure without one

### ISSUE THREAD

**Issue by Menz01** [Klangen82/Creality-Control#3]
Hello,
   tried this integration and it did not work for me and i am not sure if it should. i have Creality Ender 3 V2 and that alone has no way to add a password as it can't even be monitored remotely. so i added a creality 2.0 box that add the ability to add Wifi to the printer but still no password other than my cloudapp password.

i followed you directions and when i went to configure it, it would not accept a blank password. i then tried my cloudapp password and it wouldn't take that either.

what are the specs needed to run this integration?

**Comment by Klangen82** [comment]
Hello Menz01,

I haven't used the Creality Wifi Box before, and from what I understand, it
only supports cloud connectivity and not websocket connections, correct? I
quickly looked this up on Google, but if there's a way to use websocket
communication, then perhaps you or we together could develop support for
this box.

**Comment by Menz01** [comment]
from what i can tell its only cloud. i am certainly not knowledgeable enough to help beyond testing things. i appreciate your reply you may close this issue as i will look for something else if there is even one.
