### ISSUE TITLE
password 

### ISSUE THREAD

**Issue by VietnamecDevelopment** [Klangen82/Creality-Control#4]
my printer doesnt have password set, its Creality Ender 3 V3 KE, but its required to put the password there, can u make it optional?

**Comment by Klangen82** [comment]
Hi @VietnamecDevelopment 

Do you know if the web socket will work without authentication, have tested this?

**Comment by VietnamecDevelopment** [comment]
Hi, i havent tested that.. but i cannot connect my printer to hass because i dont have any password set.

**Comment by Klangen82** [comment]
I don't have your printer, so I can't verify if it supports WebSocket calls. Therefore, it's best for you to check if the printer responds to WebSocket requests first.

To determine the commands sent to my printer, I used Wireshark to monitor the commands sent by the Creality Halot Box software. Please try to figure this out, and then we can see if we can remove the password.

**Comment by VietnamecDevelopment** [comment]
i have no clue how to do this..

**Comment by Klangen82** [comment]
Okay, but can you monitor the printer using the Creality Halot Box software?

**Comment by VietnamecDevelopment** [comment]
i've never heard of that software
